# fly.toml app configuration file generated for threeblind-api on 2023-11-09T11:20:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "threeblind-api"
primary_region = "atl"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
